/** "Explain this": plain-word explanations built from the rule's own fields.
 *
 *  Nothing here is generated by a model. Every sentence is assembled from the
 *  review_rules row, the red-flag rule, the phase's required documents, or the
 *  status rule, plus the values on the record that made it fire.
 */

import type { AcqRow, BoardEntry, RequiredDoc } from "@/lib/launch-sequence";
import type { RedFlag } from "@/lib/intake";

export type Explanation = {
  /** What fired. */
  heading: string;
  /** Why it fired, in plain words, from the record. */
  why: string[];
  /** The rule text, as written in the table it came from. */
  rule: string | null;
  /** The citation carried by that rule. */
  citation: string | null;
  /** What would clear it. */
  clears: string[];
  /** The rule's own note, when it has one. */
  note?: string | null;
};

function answerYes(acq: AcqRow, needle: RegExp): string | null {
  const answers = acq.nf1707_answers;
  if (!answers || typeof answers !== "object") return null;
  for (const [k, v] of Object.entries(answers as Record<string, unknown>)) {
    if (needle.test(k) && (v === "1" || v === true || /yes/i.test(String(v)))) return k;
  }
  return null;
}

function money(v: unknown): string {
  const n = Number(v);
  if (!Number.isFinite(n)) return "not recorded";
  return n.toLocaleString("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });
}

/** The evidence on the record that made a review rule apply. */
function reviewEvidence(role: string, acq: AcqRow): string[] {
  const r = role.toLowerCase();
  const value = money(acq.estimated_value);
  if (r.startsWith("aviation safety")) {
    const key = answerYes(acq, /S5V/i);
    return [
      key
        ? `NF 1707 Section 5.V is answered yes on this record (answer ${key}): the requirement covers the acquisition or use of aircraft.`
        : "NF 1707 Section 5.V is answered yes on this record: the requirement covers the acquisition or use of aircraft.",
    ];
  }
  if (r.startsWith("legal review"))
    return [
      String(acq.jofoc_authority_citation ?? "").trim()
        ? "A JOFOC authority is recorded, so the file carries a justification for other than full and open competition."
        : `The estimated value ${value} is at or above the trigger value in effect for this Center.`,
    ];
  if (r.startsWith("pricing review"))
    return [
      /cost/i.test(String(acq.contract_type ?? ""))
        ? `The contract type is recorded as ${acq.contract_type}.`
        : `The estimated value ${value} is at or above the certified cost or pricing data threshold in effect.`,
    ];
  if (r.startsWith("small business")) return [`The estimated value ${value} is above the micro-purchase threshold.`];
  if (r.startsWith("cio authorization") || r.startsWith("section 508"))
    return ["The record says the requirement includes information technology."];
  if (r.startsWith("quality assurance")) return ["The record says this requirement has a hardware deliverable."];
  if (r.startsWith("flight operations"))
    return [`The enterprise strategy check on the record reads ${acq.enterprise_psl_check ?? "not recorded"}.`];
  if (r.startsWith("enterprise strategy"))
    return [
      `The estimated value ${value} is above the simplified acquisition threshold and the requirement matches an enterprise strategy with required coordination.`,
    ];
  if (r.startsWith("public announcement"))
    return [`The estimated value ${value} is at or above the trigger and the set-aside reads ${acq.set_aside ?? "not recorded"}.`];
  return [`The estimated value ${value} meets the trigger written in the review rule.`];
}

export function explainReview(entry: BoardEntry, acq: AcqRow): Explanation {
  const clears: string[] =
    entry.vote === "no-go"
      ? [
          `${entry.reviewer_name} recorded a No-go${entry.reason ? `: ${entry.reason}` : ""}. The file clears when that is resolved and the reviewer records a Go.`,
        ]
      : entry.vote === "go"
        ? [`${entry.reviewer_name} recorded a Go, so this review no longer holds the file.`]
        : [
            entry.poll_id
              ? `${entry.reviewer_name} records a Go on the poll for ${entry.phase}. A No-go needs a reason.`
              : `Open the poll for ${entry.phase}, then ${entry.reviewer_name} records a Go.`,
          ];
  if (entry.planned_days != null)
    clears.push(`The review is planned to take ${entry.planned_days} days.`);
  return {
    heading: `${entry.reviewer_role} applies to this acquisition`,
    why: reviewEvidence(entry.reviewer_role, acq),
    rule: entry.trigger,
    citation: entry.citation,
    clears,
    note: entry.note,
  };
}

export function explainRedFlag(flag: RedFlag): Explanation {
  return {
    heading: flag.title,
    why: [
      flag.blocking
        ? "This flag blocks the clock: the record does not yet satisfy the rule below."
        : "This flag does not block the clock, but the record does not yet satisfy the rule below.",
      flag.detail,
    ],
    rule: flag.title,
    citation: flag.citation ?? null,
    clears: [flag.detail],
  };
}

/**
 * Why a launch-sequence row exists at all: what the file needs it for, written
 * from the row's own purpose in the contract file. Nothing here is generated.
 */
const ROW_PURPOSE: { match: RegExp; purpose: string }[] = [
  { match: /NF 1707/i, purpose: "The intake record is the requirement as the requester stated it. Every later document reads its facts from this row, so it is the first thing the file needs." },
  { match: /cost estimate|IGCE/i, purpose: "The independent estimate is the government's own view of a fair price. Price reasonableness is judged against it, so it has to exist before quotations are seen." },
  { match: /statement of work|performance work statement/i, purpose: "The work description is what the quoters price and what the government later accepts. Without it there is nothing to solicit or to inspect against." },
  { match: /market research/i, purpose: "The research memorandum records what the market can supply, whether commercial items meet the need, and whether two or more small businesses can compete. The acquisition method rests on it." },
  { match: /NF 1787/i, purpose: "The small business coordination record shows the set-aside decision was considered with the small business specialist before the requirement was released." },
  { match: /other than full and open competition|limited sources|brand name/i, purpose: "The justification is the written basis for not competing the requirement. Without it the file cannot support a sole-source or restricted award." },
  { match: /notice of intent/i, purpose: "The notice tells the market a sole-source award is planned and gives other sources a chance to respond before award." },
  { match: /synopsis|solicitation notice/i, purpose: "The public notice is how the requirement reaches the market. It carries the quote instructions and the response date." },
  { match: /NCMS handoff/i, purpose: "The solicitation and award are written in NCMS. This packet carries the facts and the clause set across so nothing is retyped." },
  { match: /funds certified/i, purpose: "Funds have to be available for the period of performance before the government obligates. The certification is the record that they are." },
  { match: /proposed price/i, purpose: "The proposed price from the intended source is what the negotiation memorandum and the price reasonableness determination are built on." },
  { match: /evaluation of quotations/i, purpose: "The evaluation record shows how each quotation was measured against the stated criteria and who was recommended for award." },
  { match: /negotiation memorandum|PNM/i, purpose: "The memorandum is the determination of record that the price is fair and reasonable, and the story of how that conclusion was reached." },
  { match: /SAM\.gov|exclusion/i, purpose: "Award cannot go to an excluded party. The registration and exclusion check is the evidence that the intended awardee was clear at the time of award." },
  { match: /integrity records|FAPIIS/i, purpose: "The integrity records are part of the responsibility picture the contracting officer signs to." },
  { match: /SF 1449 signature/i, purpose: "The contracting officer's signature on the SF 1449 is the affirmative determination of responsibility and the act of award." },
  { match: /recorded votes/i, purpose: "Each required reviewer votes by name, so the file shows who cleared the action and who did not." },
  { match: /FPDS/i, purpose: "The contract action report puts the award into the federal record. The file is not complete until it is reported." },
  { match: /CPARS|past performance/i, purpose: "The performance evaluation is what future buyers read when they assess this contractor." },
  { match: /COR appointment/i, purpose: "The appointment letter names who may act on the government's behalf during performance and what they may not do." },
  { match: /option exercise/i, purpose: "Exercising an option is a unilateral act with conditions. The notice and the determination are the record that they were met." },
  { match: /SF 30/i, purpose: "The modification packet carries the change, its authority, and the clause effect so the change is administered from one record." },
  { match: /closeout/i, purpose: "Closeout settles the money, the property, and the claims, and closes the file for retention." },
  { match: /contract file complete/i, purpose: "The complete file is what an auditor, a protest, or a successor contracting officer reads years from now." },
];

function rowPurpose(doc: RequiredDoc): string {
  const hit = ROW_PURPOSE.find((p) => p.match.test(doc.label));
  if (hit) return hit.purpose;
  return `${doc.label} is part of the contract file for this action: it records a fact or a decision that later documents and reviewers rely on.`;
}

/** Why a launch-sequence row is on this file, satisfied or not. */
export function explainDocRow(doc: RequiredDoc, phase: string, satisfied: boolean): Explanation {
  const why = [rowPurpose(doc)];
  why.push(
    doc.optional
      ? `${phase} offers this row. It never holds the clock and never blocks the exit from the phase.`
      : `${phase} requires this row, so the file cannot leave the phase until the record shows it.`,
  );
  why.push(
    satisfied
      ? "The record shows it, so this row is satisfied."
      : "The record does not show it yet.",
  );
  return {
    heading: satisfied ? `Why ${doc.label} is on this file` : `${doc.label} is missing`,
    why,
    rule: `${phase} ${doc.optional ? "offered" : "required"} row: ${doc.label}`,
    citation: doc.citation,
    clears: satisfied
      ? ["Nothing is outstanding on this row."]
      : [
          doc.field
            ? `Attach it and mark it on the file. The hold lifts as soon as the record shows it.`
            : `Produce it from the template or the check it links to. The hold lifts as soon as the file shows it.`,
        ],
    note: doc.note ?? null,
  };
}

export function explainMissingDoc(doc: RequiredDoc, phase: string): Explanation {
  return explainDocRow(doc, phase, false);
}


export function explainHold(
  hold: { reason: string; owner: string },
  acq: AcqRow,
): Explanation {
  // "Intake: IGCE is missing" reads as a field code on screen, so the same fact
  // is stated as a calm sentence here.
  const missing = /^(.+?):\s*(.+?)\s+is missing$/i.exec(hold.reason);
  const noGo = /^No-go:\s*(.+)$/i.exec(hold.reason);
  const unvoted = /^(.+?)\s+has not voted$/i.exec(hold.reason);
  const sentence = missing
    ? `The ${missing[2]} is not yet on the file for the ${missing[1]!.toLowerCase()} phase.`
    : noGo
      ? `A reviewer recorded a No-go: ${noGo[1]}.`
      : unvoted
        ? `${unvoted[1]} has not recorded a vote yet.`
        : hold.reason;
  return {
    heading: "This file is on hold",
    why: [
      sentence,
      `${hold.owner} owns the hold.`,
      acq['hold_started_at']
        ? `The hold started on ${String(acq['hold_started_at']).slice(0, 10)}.`
        : "The hold start time is not recorded.",
    ],
    rule: "A file holds while a required document is missing, a reviewer has voted No-go, or a review left behind has not voted.",
    citation: "FAR 4.801 (contract file); Center policy for the review chain",
    clears: [
      "The hold lifts by itself once the cause is cleared: attach the missing document, resolve the No-go, or record the missing vote.",
    ],
  };
}

export function explainStatus(args: {
  status: string;
  clockState: string | null;
  holdReason: string | null;
  scheduleImpactDays: number | null;
  behindPhase: string | null;
  pollDueSoon: string | null;
}): Explanation {
  const why: string[] = [];
  if (args.status === "Launched") why.push("The award is recorded, so the file reads Launched.");
  if (args.clockState === "hold" && args.holdReason) why.push(`The file is on hold: ${args.holdReason}.`);
  if (args.scheduleImpactDays !== null && args.scheduleImpactDays < 0)
    why.push(
      `The forecast award plus delivery lands ${Math.abs(args.scheduleImpactDays)} days after the mission date.`,
    );
  if (args.behindPhase) why.push(`${args.behindPhase} has run past its planned days.`);
  if (args.pollDueSoon) why.push(`A vote from ${args.pollDueSoon} is due within three days.`);
  if (!why.length)
    why.push("Nothing is holding the file, no phase has run past its planned days, and no vote is due within three days.");
  return {
    heading: `Status: ${args.status}`,
    why,
    rule: "Launched when the award is recorded. At Risk on a hold or when the forecast award lands after the mission date. Needs Attention when a phase has run past its planned days or a vote is due within three days. Otherwise On Track.",
    citation: "phase_plan and review_rules (planned days); mission milestone date",
    clears:
      args.status === "At Risk"
        ? ["Lift the hold, or recover days in the remaining phases so the forecast award lands before the mission date."]
        : args.status === "Needs Attention"
          ? ["Finish the phase that has run long, or record the vote that is coming due."]
          : ["Nothing to clear."],
  };
}

export function explainWarrant(args: {
  coName: string;
  value: number;
  limit: number;
}): Explanation {
  return {
    heading: "The estimated value is above the assigned warrant",
    why: [
      `The estimated value is ${money(args.value)} and the warrant recorded for ${args.coName} is ${money(args.limit)}.`,
    ],
    rule: "An acquisition may not be awarded above the warrant of the contracting officer who signs it.",
    citation: "FAR 1.602-1 (contracting officer authority); NFS 1801.603",
    clears: [
      `Assign a contracting officer whose warrant is at or above ${money(args.value)}, or reduce the estimated value.`,
    ],
  };
}
