// NEAR file-structure crosswalk.
//
// Source: NEAR File Structure Checklist.xlsx · Crosswalk WSC (v3.3, Apr 24).
// Columns: 1098 TAB NUMBER, VISUAL ORDER ON NEAR FE SCREEN, NEAR File Element
// Title, NEAR UNIQUE ID, NEAR FE Notes.
//
// The rows below are the checklist as published. Nothing is invented: the
// template map only names T-Minus templates that match a checklist element,
// and a template with no honest match is simply absent. Advisory only — the
// crosswalk never holds a phase exit, and NCMS stays the system of record.

export const NEAR_CROSSWALK_SOURCE = "NEAR File Structure Checklist.xlsx \u00b7 Crosswalk WSC (v3.3, Apr 24)";

export type NearElement = {
  /** Tab as printed on the checklist, which may read like "2 or 36" or "n/a". */
  tab: string;
  /** First tab number on that label, or null where the checklist prints none. */
  tabPrimary: number | null;
  visualOrder: number;
  title: string;
  uid: string;
  notes: string;
};

export const NEAR_ELEMENTS: NearElement[] = [
  { tab: "13", tabPrimary: 13, visualOrder: 1, title: "Purchase Request (PR), NF 1707", uid: "1", notes: "\u00b7 Copy of PR from SAP\n\u00b7 NF 1707, Special Approvals and Affirmation (file attachments in appropriate file element)\n\u00b7 Suggested sources" },
  { tab: "13", tabPrimary: 13, visualOrder: 2, title: "Enterprise License Management Team (ELMT) Documentation", uid: "15", notes: "" },
  { tab: "13", tabPrimary: 13, visualOrder: 3, title: "Capitalization Determination Form (NF 1739)", uid: "43", notes: "\u00b7 NF 1739 attached to the NF 1707" },
  { tab: "13", tabPrimary: 13, visualOrder: 4, title: "Independent Government Cost Estimate (IGCE)", uid: "13", notes: "\u00b7 Government cost estimates" },
  { tab: "2 or 36", tabPrimary: 2, visualOrder: 5, title: "Requirements Development Team Appointment Letter(s)", uid: "2", notes: "\u00b7 Requirements Development Team Request & Appointment Letters NASA HQ templates" },
  { tab: "13", tabPrimary: 13, visualOrder: 6, title: "Statement Of Work (SOW)/Performance Work Statement (PWS)/Specification/Drawings", uid: "4", notes: "\u00b7 Initial work statement/specifications/drawings" },
  { tab: "13", tabPrimary: 13, visualOrder: 7, title: "Preliminary Government Quality Assurance Surveillance Plan (QASP)", uid: "56", notes: "\u00b7 Preliminary QASP" },
  { tab: "7", tabPrimary: 7, visualOrder: 8, title: "Classified Requirements (DD 254)", uid: "39", notes: "\u00b7 DD 254, Department of Defense Contract Security Classification Specification" },
  { tab: "5", tabPrimary: 5, visualOrder: 9, title: "Strategic Sourcing", uid: "8", notes: "\u00b7 Strategic sourcing documentation attached to the NF 1707" },
  { tab: "8", tabPrimary: 8, visualOrder: 10, title: "Set-Aside Consideration/Recommendations/Small Business Coordination", uid: "7", notes: "\u00b7 NF 1787, Small Business Coordination \n\u00b7 Supporting documentation in connection with determining method of procurement of SB goal" },
  { tab: "9", tabPrimary: 9, visualOrder: 11, title: "Small Business Administration (SBA)-provided 8(a) Information", uid: "14", notes: "\u00b7 8(a) offering letter to SBA \n\u00b7 SBA acceptance letter \n\u00b7 SBA Selection Notification/Letter\n\u00b7 Separate offers and acceptances for repetitive acquisitions \n\u00b7 Request and acceptance of 8(a) release from the program" },
  { tab: "4", tabPrimary: 4, visualOrder: 12, title: "RFI/Sources Sought Synopsis/Responses", uid: "10", notes: "\u00b7 All sources sought synopses\n\u00b7 Special and advance notices \n\u00b7 All responses to sources sought synopses\n\u00b7 Evaluations conducted of sources sought synopses\n\u00b7 Sources sought notice posting requirement >$50M\n\u00b7 Governmentwide Point of Entry (GPE) NASA HQ templates\n\u00b7 Electronic Document Posting Checklist NASA HQ template" },
  { tab: "4", tabPrimary: 4, visualOrder: 13, title: "Market Research Analysis", uid: "9", notes: "\u00b7 Ability One Coordination NASA HQ template \n\u00b7 NF 1787A, Market Research Report" },
  { tab: "17", tabPrimary: 17, visualOrder: 14, title: "Exception to Fair Opportunity/Brand Name Justification", uid: "24", notes: "\u00b7 FAIR Opportunity Exception \u2013 Brand Name Justification NASA HQ template" },
  { tab: "15", tabPrimary: 15, visualOrder: 15, title: "Justification for Other than Full and Open Competition (JOFOC)", uid: "22", notes: "\u00b7 JOFOC NASA HQ Template\n\u00b7 JOFOC Sole Source 8(a) Award or Modification Greater Than $25M NASA HQ template" },
  { tab: "16", tabPrimary: 16, visualOrder: 16, title: "GSA Limited Sources Justifications (LSJ)", uid: "23", notes: "\u00b7 LSJ GSA Federal Supply Schedule (FSS) NASA HQ template" },
  { tab: "18", tabPrimary: 18, visualOrder: 17, title: "Organizational Conflict of Interest (OCI)/Limitation on Future Contracting Memo", uid: "51", notes: "\u00b7 OCI Limitation of Future Contracting Memo NASA HQ template\n\u00b7 OCI Determination Memo and Checklist NASA HQ template" },
  { tab: "18", tabPrimary: 18, visualOrder: 18, title: "Organizational Conflict of Interest (OCI) Waiver/Decision (Pre-Award)", uid: "37", notes: "\u00b7 Documentation/decision surrounding any identified OCI issues\n\u00b7 OCI waiver" },
  { tab: "10", tabPrimary: 10, visualOrder: 19, title: "Subcontracting Goals", uid: "12", notes: "\u00b7 Recommended subcontracting goals document" },
  { tab: "3", tabPrimary: 3, visualOrder: 20, title: "Contract Type Determination & Findings (D&F)", uid: "17", notes: "\u00b7 CO determination to use a contract with economic price adjustment \n\u00b7 Documentation of advanced approval for use of clauses using cost indexes \n\u00b7 CO waiver for contractor requirement to cost share \n\u00b7 D&F Authority to Execute a CPAF Contract NASA HQ template \n\u00b7 D&F Authority to Execute a CPIF Contract NASA HQ template\n\u00b7 D&F Commercial T&M of Labor Hour Contract/Order NASA HQ template \n\u00b7 D&F Noncommercial T&M or Labor Hour Contract/Order NASA HQ template \n\u00b7 D&F GSA T&M or Labor Hr Order NASA HQ t" },
  { tab: "11", tabPrimary: 11, visualOrder: 21, title: "Indefinite Delivery Indefinite Quantity (IDIQ)/Blanket Purchase Agreement (BPA) Single Award Determination", uid: "18", notes: "\u00b7 D&F Single Award IDIQ Contract Over $100M NASA HQ template\n\u00b7 D&F Single Award GSA, FSS, BPA over $100M NASA HQ template" },
  { tab: "24", tabPrimary: 24, visualOrder: 22, title: "Option Justification", uid: "28", notes: "\u00b7 Option Justification NASA HQ template\n\u00b7 Option Exercise Determination NASA HQ template\n\u00b7 Technical input\n\u00b7 Option Exercise Contractor Preliminary Notification NASA HQ template" },
  { tab: "33", tabPrimary: 33, visualOrder: 23, title: "Five Year Deviation/NFS Deviations/Other", uid: "27", notes: "\u00b7 Deviation Request 5-Year Period of Performance Limitation for Contracts NASA HQ template\n\u00b7 FAR & NFS Deviation Request NASA HQ template\n\u00b7 Deviation Request 5-Year Period of Performance Limitation for Economy Act Interagency Agreements and Orders NASA HQ template\n\u00b7 Documentation for deviations not covered by another file element\n\u00b7 Request for Legal Review, and disposition if applicable" },
  { tab: "66", tabPrimary: 66, visualOrder: 24, title: "Advance Payment Determination", uid: "31", notes: "\u00b7 Contractor's written request\n\u00b7 CO determination" },
  { tab: "25", tabPrimary: 25, visualOrder: 25, title: "Buy American Act Exception Determination", uid: "32", notes: "\u00b7 Buy American Act exception determination\n\u00b7 Buy American Act Nonavailability Determination \u2013 Supplies NASA HQ template" },
  { tab: "30", tabPrimary: 30, visualOrder: 26, title: "Pension Portability Determination", uid: "33", notes: "\u00b7 Pension portability determination" },
  { tab: "33", tabPrimary: 33, visualOrder: 27, title: "NASA Performance Incentive Exception Determination", uid: "35", notes: "\u00b7 Approved exception to including technical performance incentives" },
  { tab: "21, 22, 23, or n/a", tabPrimary: 21, visualOrder: 28, title: "Economy Act or Other Determinations & Findings", uid: "34", notes: "\u00b7 D&F Authority to Exclude a Source NASA HQ template \n\u00b7 D&F Interagency Acquisitions Economy Act NASA HQ template \n\u00b7 D&F for Bundled Requirements NASA HQ template\n\u00b7 D&F for Consolidation of Requirements NASA HQ template\n\u00b7 Bid Samples Justification \n\u00b7 Descriptive Literature Justification" },
  { tab: "3", tabPrimary: 3, visualOrder: 29, title: "NF 533Q Waiver", uid: "36", notes: "\u00b7 NF 533Q waiver" },
  { tab: "14", tabPrimary: 14, visualOrder: 30, title: "Contracting Officer's Memo to Provide Property", uid: "30", notes: "\u00b7 CO Determination to Provide Government Property NASA HQ template" },
  { tab: "32", tabPrimary: 32, visualOrder: 31, title: "Request to Award a Foreign Contract", uid: "19", notes: "\u00b7 D&F for waiver of right to examination of records \n\u00b7 Request to Award a Foreign Contract NASA HQ template (if greater than $100K or involved export control issues)\n\u00b7 HQ concurrence on MOUs with foreign entities and other type of international agreements" },
  { tab: "66", tabPrimary: 66, visualOrder: 32, title: "Advance Agreements - Pre-Contract Costs", uid: "16", notes: "\u00b7 Precontract Costs Approval Memo and Authorization Letter to Contractor NASA HQ template" },
  { tab: "2", tabPrimary: 2, visualOrder: 33, title: "Acquisition Plan/Procurement Strategy Meeting (PSM)", uid: "20", notes: "\u00b7 PSM Signature Page NASA HQ template\n\u00b7 PSM for Contracts NASA HQ template (charts, initial and revised)\n\u00b7 Approved minutes of the PSM\n\u00b7 Written Acquisition Plan for Contracts NASA HQ template\n\u00b7 Compliance with Ethical Obligations (Self Certification) NASA HQ template\n\u00b7 Addendum Outlining Significant changes to Approved PSMs-Written Acquisition Plans NASA HQ template\n\u00b7 Determination ASM Not Conducted Memorandum NASA HQ template" },
  { tab: "28", tabPrimary: 28, visualOrder: 34, title: "Justification and Approvals for UCAs/Letter Contracts", uid: "48", notes: "\u00b7 UCA-Letter Contract Justification NASA HQ template" },
  { tab: "n/a", tabPrimary: null, visualOrder: 35, title: "Approval to locate the contractor onsite", uid: "29", notes: "\u00b7 In accordance with Center policy" },
  { tab: "31", tabPrimary: 31, visualOrder: 36, title: "System for Award Management (SAM) Exclusion Verification Documentation", uid: "21", notes: "\u00b7 SAM exclusions verification for sole source awards" },
  { tab: "30", tabPrimary: 30, visualOrder: 37, title: "Notification to Interested Parties under Collective Bargaining Agreements (CBAs)", uid: "49", notes: "\u00b7 Notification of Interested Parties under CBAs NASA HQ template" },
  { tab: "19", tabPrimary: 19, visualOrder: 38, title: "Pre-Solicitation Synopsis/Notice, Responses, Assessment", uid: "40", notes: "\u00b7 Pre-solicitation synopsis/notice posting\n\u00b7 BAA synopsis (e.g., NRA, Early Career Initiative (ECI), AO)\n\u00b7 Responses \n\u00b7 Assessment of responses" },
  { tab: "6", tabPrimary: 6, visualOrder: 39, title: "Pre-Solicitation Conference", uid: "41", notes: "\u00b7 All documentation associated with pre-solicitation discussions or conferences\n\u00b7 Written or oral questions or comments received\n\u00b7 Any other pre-solicitation correspondence\n\u00b7 Attendee list" },
  { tab: "6", tabPrimary: 6, visualOrder: 40, title: "Offeror One on One Meetings Documentation", uid: "42", notes: "\u00b7 All documentation associated with one on one meetings during acquition planning phase\n\u00b7 Written or oral questions or comments received\n\u00b7 Attendee list" },
  { tab: "36", tabPrimary: 36, visualOrder: 41, title: "Source Evaluation Team (SET) Appointment Memo(s)", uid: "46", notes: "\u00b7 SET (non-SEB procedures) Membership Appointment Memorandum NASA HQ template\n\u00b7 Memorandum from the customer's manager recommending SET membership\n\u00b7 Results of OGC review (OGE 450 or SF 278) to ensure no conflicts of interest exist" },
  { tab: "36", tabPrimary: 36, visualOrder: 42, title: "Source Selection Board (SEB) Appointment Memo(s)", uid: "45", notes: "\u00b7 SEB Membership Appointment Memorandum NASA HQ template\n\u00b7 Memorandum from the customer's manager recommending SEB membership\n\u00b7 Results of OGC review (OGE 450 or SF 278) to ensure no conflicts of interest exist" },
  { tab: "36", tabPrimary: 36, visualOrder: 43, title: "Source Selection Authority Appointment Letter(s)", uid: "44", notes: "\u00b7 Source Selection Authority Appointment Letter NASA HQ template" },
  { tab: "28, 72, or n/a", tabPrimary: 28, visualOrder: 44, title: "Approval of Provisional Estimated Cost Increase", uid: "147", notes: "\u00b7 Request for Provisional Increase in the Estimated Cost NASA HQ template (for undefinitized contract actions (UCAs))" },
  { tab: "n/a", tabPrimary: null, visualOrder: 45, title: "General Correspondence (Acq. Planning Phase)", uid: "38", notes: "\u00b7 All general correspondence, documents, or requirements that are not specifically related to another acquisition planning file element" },
  { tab: "37 or 38", tabPrimary: 37, visualOrder: 46, title: "Data Requirements Descriptions (DRD) Development", uid: "50", notes: "\u00b7 DRDs" },
  { tab: "12", tabPrimary: 12, visualOrder: 47, title: "Government Furnished Property (GFP) and/or Installation Accountable Government Property (IAGP) Property List(s)", uid: "52", notes: "\u00b7 List of GFP/IAGP\n\u00b7 Center Supply & Equipment Management Officer (SEMO) and Industrial Property Officer (IPO) review \n\u00b7 Center Real Property Accountable Officer approval (1845.102-70)" },
  { tab: "29", tabPrimary: 29, visualOrder: 48, title: "e98, Request for Wage Determination", uid: "54", notes: "\u00b7 Copy of Electronic SF 98 (e98), Notice of Intention To Make a Service Contract and Response to Notice\n\u00b7 Preliminary Wage Determination\n\u00b7 Staffing Profile and input from Industry Relations Officer Collective Bargaining Agreements\n\u00b7 Labor Categories for Construction Contracts" },
  { tab: "40", tabPrimary: 40, visualOrder: 49, title: "Request For Quote (RFQ) (terms and conditions)", uid: "64", notes: "\u00b7 RFQ\n\u00b7 Amendments\n\u00b7 Industry comments/questions \n\u00b7 Electronic Document Posting Checklist NASA HQ template \n\u00b7 Synopsis" },
  { tab: "37", tabPrimary: 37, visualOrder: 50, title: "Draft RFP Reviews, Comments/Disposition, and Approvals", uid: "58", notes: "\u00b7 Draft RFP Cover Letter NASA HQ template\n\u00b7 DRFP \n\u00b7 Industry comments/questions \n\u00b7 Contracting Officer waiver of Draft RFP requirement\n\u00b7 Synopsis for draft RFP\n\u00b7 Documentation and disposition of reviewer comments (e.g., legal) \n\u00b7 Minutes from the Solicitation Review Board, including list of attendees" },
  { tab: "37", tabPrimary: 37, visualOrder: 51, title: "Draft Request for Proposal (DRFP)/Solicitation & Amendments", uid: "57", notes: "\u00b7 Draft RFP Cover Letter NASA HQ template\n\u00b7 DRFP\n\u00b7 Amendments\n\u00b7 Electronic Document Posting Checklist NASA HQ template" },
  { tab: "38", tabPrimary: 38, visualOrder: 52, title: "Final RFP Reviews, Comments/Disposition, and Approvals", uid: "55", notes: "\u00b7 FRFP Cover Letter NASA HQ template\n\u00b7 Documentation and disposition of reviewer comments (e.g., legal)\n\u00b7 Minutes from the Solicitation Review Board including list of attendees\n\u00b7 Memo required by NFS 1804.7301(b) solicitation release without certified funds\n\u00b7 Synopsis for final RFP" },
  { tab: "40", tabPrimary: 40, visualOrder: 53, title: "Final Request For Proposal (RFP)/Solicitation & Amendments", uid: "65", notes: "\u00b7 RFP Cover Letter, RFP for Non-Competitive New Awards, or RFP for Existing Contracts NASA HQ template\n\u00b7 Final RFP\n\u00b7 Industry comments/questions\n\u00b7 Amendments\n\u00b7 Electronic Document Posting Checklist NASA HQ template" },
  { tab: "40", tabPrimary: 40, visualOrder: 54, title: "Invitation for Bid (IFB)", uid: "67", notes: "\u00b7 IFB\n\u00b7 Amendments\n\u00b7 Industry comments/questions \n\u00b7 Electronic Document Posting Checklist NASA HQ template \n\u00b7 Synopsis" },
  { tab: "20", tabPrimary: 20, visualOrder: 55, title: "Broad Agency Announcement (BAA) / NASA Research Announcement (NRA) HQs Reviews and Approvals", uid: "47", notes: "\u00b7 BAA solicitation and amendments (e.g., NRA, EIC, AO)\n\u00b7 Documentation and disposition of reviewer comments (e.g., legal) for Center-issued BAAs\n\u00b7 Electronic Document Posting Checklist NASA HQ template \n\u00b7 Synopsis \n\u00b7 Broad Agency Announcement (BAA) Authority to Proceed" },
  { tab: "73", tabPrimary: 73, visualOrder: 56, title: "Request for Task Plan", uid: "201", notes: "\u00b7 Request for task proposal/plan" },
  { tab: "39", tabPrimary: 39, visualOrder: 57, title: "Blackout Notice", uid: "59", notes: "\u00b7 Blackout Notice NASA HQ template" },
  { tab: "41", tabPrimary: 41, visualOrder: 58, title: "Pre-Proposal Conference", uid: "60", notes: "\u00b7 All documentation associated with pre-bid/pre-proposal discussions or conferences\n\u00b7 Written or oral questions or comments received\n\u00b7 Any other pre-bid/pre-proposal correspondence\n\u00b7 Attendee list" },
  { tab: "41 or 56", tabPrimary: 41, visualOrder: 59, title: "Offeror One on One Meeting Documentation", uid: "189", notes: "\u00b7 All documentation associated with one on one meetings during solicitation development phase\n\u00b7 Written or oral questions or comments received\n\u00b7 Attendee list" },
  { tab: "41", tabPrimary: 41, visualOrder: 60, title: "Site Visit Documentation", uid: "61", notes: "\u00b7 All documentation associated with site visits\n\u00b7 Written or oral questions or comments received\n\u00b7 Attendee list" },
  { tab: "n/a", tabPrimary: null, visualOrder: 61, title: "General Correspondence (up to RFP Release)", uid: "63", notes: "\u00b7 All general correspondence, documents, or requirements that are not specifically related to another pre-RFP release file element" },
  { tab: "42", tabPrimary: 42, visualOrder: 62, title: "Proposal(s)/Offer(s)/Abstract of Bids", uid: "84", notes: "\u00b7 List of offerors responding \n\u00b7 All Bids/Proposals/Offers\n\u00b7 Abstract of Quotations, SF 1409, Abstract of Offers, or OP 1419, Abstract of Offer-Construction\n\u00b7 Memo from Bid Opening Officer detailing circumstances of late bid receipt\n\u00b7 Representations and certifications\n\u00b7 Results of OGC review (OGE 450 or SF 278) to ensure no conflicts of interest exist after receipt of proposals\n\u00b7 Evaluation kick-off charts or memorandum documenting kickoff meeting" },
  { tab: "42 or 45", tabPrimary: 42, visualOrder: 63, title: "System for Award Management (SAM) Verification Documentation", uid: "85", notes: "\u00b7 SAM certification entity core data: business information (screen shot) & representations and certifications" },
  { tab: "54", tabPrimary: 54, visualOrder: 64, title: "Past Performance Evaluation (i.e., CPARS, PPQs)", uid: "190", notes: "\u00b7 Past Performance evaluation report/documentation\n\u00b7 Past Performance Questionnaires\n\u00b7 CPARS evaluations reviewed to support source selection\n\u00b7 Other supporting documentation" },
  { tab: "54", tabPrimary: 54, visualOrder: 65, title: "Technical Evaluation", uid: "74", notes: "\u00b7 Documentation of unacceptable proposals, including OGC review\n\u00b7 Individual and consensus scoring sheets\n\u00b7 Technical evaluation report (for all evaluation factors)\n\u00b7 NASA Technical Evaluation Report NASA HQ template (for sole source procurements)" },
  { tab: "54 or 62", tabPrimary: 54, visualOrder: 66, title: "Cost/Price Analysis", uid: "73", notes: "\u00b7 Cost/Price analysis report\n\u00b7 Audit reports supporting the cost/price analysis\n\u00b7 Other applicable supporting documentation\n\u00b7 Copy of NF 1434, Letter of Request for Pricing-Audit-Technical Evaluation Services, if necessary\n\u00b7 Evaluation of Compensation for Professional Employees - Total Compensation Plan Evaluation NASA HQ template" },
  { tab: "56", tabPrimary: 56, visualOrder: 67, title: "Exchanges with Offerors After Receipt of Proposals", uid: "89", notes: "\u00b7 Letters notifying offerors that their proposal has been identified as unacceptable for further evaluation\n\u00b7 Record of clarification/exchanges conducted with unsuccessful and successful offerors prior to the establishment of the competitive range/finalists\n\u00b7 Any correspondence or records of telecoms or meetings relating to any communication conducted\n\u00b7 Offeror responses to Government questions/clarifications/exchanges\n\u00b7 Record of oral discussions held (presentation material, attendee list, minu" },
  { tab: "57", tabPrimary: 57, visualOrder: 68, title: "Competitive Range Determination & Notifications", uid: "90", notes: "\u00b7 Competitive range determination\n\u00b7 Letters notifying offerors that they were not included in the competitive range\n\u00b7 Request for Final Proposal Revisions (FPR)" },
  { tab: "61", tabPrimary: 61, visualOrder: 69, title: "Debriefings (Pre-Award)", uid: "93", notes: "\u00b7 Offeror(s) request for pre-award debriefing\n\u00b7 Debriefing charts\n\u00b7 Official summary of the debriefing (date, time, place, attendees, information conveyed, questions, and answers)" },
  { tab: "58", tabPrimary: 58, visualOrder: 70, title: "Discussions", uid: "91", notes: "\u00b7 Any correspondence or records of telecoms or meetings relating to any negotiations conducted after competitive range" },
  { tab: "59", tabPrimary: 59, visualOrder: 71, title: "Final Proposal Revision (FPR) Submissions", uid: "92", notes: "\u00b7 All FPRs" },
  { tab: "n/a", tabPrimary: null, visualOrder: 72, title: "FPR Technical Evaluation", uid: "191", notes: "\u00b7 Final individual and consensus scoring sheet revisions\n\u00b7 Final consensus evaluation findings (for all factors)" },
  { tab: "n/a", tabPrimary: null, visualOrder: 73, title: "FPR Past Performance Evaluation", uid: "192", notes: "\u00b7 Final performance evaluation report" },
  { tab: "n/a", tabPrimary: null, visualOrder: 74, title: "FPR Cost/Price Analysis", uid: "193", notes: "\u00b7 Final cost/price analysis report\n\u00b7 Other applicable supporting documentation" },
  { tab: "63", tabPrimary: 63, visualOrder: 75, title: "Prenegotiation Objectives and NF634", uid: "81", notes: "\u00b7 Pre-negotiation Position Memorandum (PPM) NASA HQ template (for non-competitive acquisitions greater than SAT)\n\u00b7 NF634, Structured Approach Profit/Fee Objective \n\u00b7 Documentation and disposition of reviewer comments (e.g., legal, HQ)\n\u00b7 HQ approval, when applicable \n\u00b7 Pre-negotiation Review Committee (PRC) Report\n\u00b7 PRC Memo for Record (MFR)\n\u00b7 Procurement Officer PRC waiver" },
  { tab: "65", tabPrimary: 65, visualOrder: 76, title: "Price Negotiation Memorandum", uid: "82", notes: "\u00b7 Price Negotiation Memorandum (PNM) \n\u00b7 PNM NASA HQ template (for non-competitive acquisition greater than the SAT)\n\u00b7 Combined PPM & PNM (\"Stand-Alone\" Document) - All documents normally filed under FE 75 will be filed with the\ncombined document here\n\u00b7 Request for legal review, and disposition of comments if combined PPM & PNM\n\u00b7 Negotiation memo submittal (send to DCAA when audit or specialized services were performed)" },
  { tab: "62", tabPrimary: 62, visualOrder: 77, title: "Price Reasonableness Determination", uid: "202", notes: "" },
  { tab: "64", tabPrimary: 64, visualOrder: 78, title: "Certificate of Current Cost or Pricing Data", uid: "83", notes: "\u00b7 Executed Certificate of Current Cost or Pricing Data\n\u00b7 Determination that adequate price competition exists when single proposal is received in a competition\n(15.403-1(c)(1)(ii)(B))" },
  { tab: "45", tabPrimary: 45, visualOrder: 79, title: "Pre-Award Survey", uid: "80", notes: "\u00b7 Pre-Award survey" },
  { tab: "45", tabPrimary: 45, visualOrder: 80, title: "Responsibility Determination", uid: "68", notes: "\u00b7 FAPIIS & SAM.Gov documentation in support of the Government\u2019s responsibility assessment\n\u00b7 SAM responsibility and qualification information, including exclusions (screen shot) \n\u00b7 Other Supporting documentation\n\u00b7 Determination of Responsibility Non-responsibility NASA HQ template" },
  { tab: "46", tabPrimary: 46, visualOrder: 81, title: "Certificate of Competency Action", uid: "70", notes: "\u00b7 CO referral to appropriate SBA Government Contracting Area Office \n\u00b7 SBA Certificate of Competency (COC) \n\u00b7 Appeal and supporting documentation" },
  { tab: "45", tabPrimary: 45, visualOrder: 82, title: "Audits (DCAA, DCMA, EPO, etc.)", uid: "71", notes: "\u00b7 Audit reports supporting evaluation phase" },
  { tab: "47", tabPrimary: 47, visualOrder: 83, title: "Equal Employment Opportunity (EEO) Compliance Review", uid: "86", notes: "\u00b7 Evidence of EEO pre-award compliance checks (print screen)\n\u00b7 EEO pre-Award clearance request" },
  { tab: "47", tabPrimary: 47, visualOrder: 84, title: "Veterans Employment and Training Service (VETS) 4212 Compliance Review", uid: "87", notes: "\u00b7 Evidence of VETS compliance (print screen)" },
  { tab: "43", tabPrimary: 43, visualOrder: 85, title: "Mistakes in Bids/Bid Verification", uid: "99", notes: "\u00b7 Documentation related to mistakes in bids including OGC review" },
  { tab: "60", tabPrimary: 60, visualOrder: 86, title: "Source Selection Presentation/Decision", uid: "94", notes: "\u00b7 Written reports or charts briefed to SSA\n\u00b7 CO evaluation regarding single proposal received or number of proposals received equals number of awards contemplated\n\u00b7 Request for legal review, and disposition of comments\n\u00b7 Final signed source selection statement\n\u00b7 BAA (e.g., NRA, EIC, AO) source selection decision" },
  { tab: "69", tabPrimary: 69, visualOrder: 87, title: "Small Business Set-Aside Pre-Award Notice", uid: "101", notes: "\u00b7 SB Set-Aside Pre-Award Apparent Successful Offeror Notification NASA HQ template" },
  { tab: "69", tabPrimary: 69, visualOrder: 88, title: "Unsuccessful/Successful Offeror Letters", uid: "102", notes: "\u00b7 Post-Award Notification Letter to Unsuccessful Offerors NASA HQ template\n\u00b7 Post-Award Notification Letter to Successful Offeror NASA HQ template\n\u00b7 Notice to Award (14.408-1 Sealed Bid)" },
  { tab: "87", tabPrimary: 87, visualOrder: 89, title: "Notice of Award (Construction)", uid: "95", notes: "\u00b7 Evidence of construction award notice \n\u00b7 Notice to proceed" },
  { tab: "88", tabPrimary: 88, visualOrder: 90, title: "Bid/payment/performance bonds and insurance", uid: "96", notes: "\u00b7 Bid bond\n\u00b7 Performance & payment bonds\n\u00b7 Construction Bond Checklist NASA HQ template\n\u00b7 Certificate of liability insurance" },
  { tab: "44", tabPrimary: 44, visualOrder: 91, title: "IFB/RFP Cancellation/Rejection Determination", uid: "88", notes: "\u00b7 Determination to cancel\n\u00b7 COR/Technical POC's supporting documentation for cancellation/rejection\n\u00b7 Notice of cancellation" },
  { tab: "71", tabPrimary: 71, visualOrder: 92, title: "Protests (Pre-Award)", uid: "194", notes: "\u00b7 Protest notification letter\n\u00b7 Size standard protest notification to the appropriate SBA Government Contracting Area Director \n\u00b7 Submitted protest\n\u00b7 Government's response to protest\n\u00b7 Protest decision \n\u00b7 CO determination to award to protect the public interest" },
  { tab: "n/a", tabPrimary: null, visualOrder: 93, title: "General Correspondence (Pre-Award)", uid: "195", notes: "\u00b7 All general correspondence, documents, or requirements that are not specifically related to another pre-award file element" },
  { tab: "68", tabPrimary: 68, visualOrder: 94, title: "Contract Reviews and Approvals", uid: "105", notes: "\u00b7 Documentation and disposition of reviewer comments" },
  { tab: "70", tabPrimary: 70, visualOrder: 95, title: "Administrators Notification of Significant Contract Action (ANOSCA) and/or Public Announcement", uid: "106", notes: "\u00b7 Review/approval of ANOSCA/public announcement \n\u00b7 ANOSCA or HQ public announcement (1805.303-71)\n\u00b7 NASA Notification of Contract Action NASA HQ template" },
  { tab: "n/a", tabPrimary: null, visualOrder: 96, title: "Contract (Base Award)", uid: "110", notes: "\u00b7 Executed contract and all attachments\n\u00b7 Conformed contract" },
  { tab: "68", tabPrimary: 68, visualOrder: 97, title: "FPDS Contract Action Report (CAR)", uid: "112", notes: "\u00b7 FPDS-NG printout and related review correspondence" },
  { tab: "61", tabPrimary: 61, visualOrder: 98, title: "Debriefings (Post-Award)", uid: "196", notes: "\u00b7 Offeror(s) request for post-award debriefing\n\u00b7 Debriefing charts\n\u00b7 Official summary of the debriefing (date, time, place, attendees, information conveyed, questions, and answers)" },
  { tab: "72", tabPrimary: 72, visualOrder: 99, title: "Executed Modification", uid: "135", notes: "\u00b7 Modification issued" },
  { tab: "72", tabPrimary: 72, visualOrder: 100, title: "Proof of Award Distribution", uid: "197", notes: "\u00b7 For 8(a) awards, evidence of contract and modification transmission to SBA 8(a) representative \n\u00b7 For contracts with subcontracting plans, evidence of contract transmission (including final subcontracting plan) to the SBA Area Director where the contract is being performed" },
  { tab: "73", tabPrimary: 73, visualOrder: 101, title: "Executed Order", uid: "111", notes: "\u00b7 Task/delivery order or call issued" },
  { tab: "70", tabPrimary: 70, visualOrder: 102, title: "Post-Award Synopsis", uid: "108", notes: "\u00b7 Copy of award synopsis as posted on GPE\n\u00b7 HQ Electronic Document Posting Checklist template, if applicable (e.g., JOFOC)\n\u00b7 Copy of post-award posting of redacted JOFOC/Source Selection Statement (SSS) released on GPE" },
  { tab: "71", tabPrimary: 71, visualOrder: 103, title: "Protests (Post-Award)", uid: "104", notes: "\u00b7 Protest notification letter\n\u00b7 Size standard protest notification to the appropriate SBA Government Contracting Area Director \n\u00b7 Submitted protest\n\u00b7 Government's response to protest\n\u00b7 Protest decision \n\u00b7 CO determination to award to protect the public interest" },
  { tab: "74", tabPrimary: 74, visualOrder: 104, title: "Contracting Officer's Representative (COR)/Alternate COR Delegation(s)", uid: "114", notes: "\u00b7 Recommendation for Appointment of COR and/or Alternate COR NASA HQ template\n\u00b7 COR and alternate COR NF 1634(s) delegation\n\u00b7 COR \u2013 Alt. COR Cancellation Memo NASA HQ template\n\u00b7 FAC \u2013 COR Training Deferment NASA HQ template" },
  { tab: "74", tabPrimary: 74, visualOrder: 105, title: "Delegations \u2013 Audit/Admin (e.g., DCMA)", uid: "113", notes: "\u00b7 Determination to retain or modify contract administrative functions\n\u00b7 NF 1433, Letter of Audit Delegation\n\u00b7 NF1430, NF 1430A-D, Letter of Contract Administration Delegation(s)" },
  { tab: "75", tabPrimary: 75, visualOrder: 106, title: "Government Quality Assurance Surveillance Plan (QASP) & Reports", uid: "130", notes: "\u00b7 Approved Quality Assurance Surveillance Plan (QASP)\n\u00b7 QASP revisions\n\u00b7 QASP approvals\n\u00b7 Any related/applicable reports" },
  { tab: "77", tabPrimary: 77, visualOrder: 107, title: "Post-Award Conference Report/Pre-Construction Orientation", uid: "115", notes: "\u00b7 Post-Award Conference Report NASA HQ template\n\u00b7 Pre-construction Orientation Checklist NASA HQ template\n\u00b7 Procurement Officer approval to waive a post award conference\n\u00b7 Post-award letter or other written form of communication (in lieu of conference)" },
  { tab: "69", tabPrimary: 69, visualOrder: 108, title: "Notification to Interested Parties under Collective Bargaining Agreement(s)", uid: "143", notes: "\u00b7 Notification of Interested Parties under CBA\u2019s NASA HQ template" },
  { tab: "n/a", tabPrimary: null, visualOrder: 109, title: "Contractor OCI Plan & Review", uid: "78", notes: "\u00b7  OCI Plan submitted\n\u00b7 Evidence of final review and concurrence by the subject matter expert (consultant) of plan submitted \n\u00b7 Plan updates submitted and evidence of review/concurrence" },
  { tab: "n/a", tabPrimary: null, visualOrder: 110, title: "Contract Management Plan", uid: "198", notes: "\u00b7 Contract Management Plan submitted \n\u00b7 Evidence of final review and concurrence by the subject matter expert (consultant) of plan submitted \n\u00b7 Plan updates submitted and evidence of review/concurrence" },
  { tab: "n/a", tabPrimary: null, visualOrder: 111, title: "Data and Records Management Plan & Review", uid: "199", notes: "\u00b7 Data and Records Management Plan submitted \n\u00b7 Evidence of final review and concurrence by the subject matter expert (consultant) of plan submitted \n\u00b7 Plan updates submitted and evidence of review/concurrence" },
  { tab: "91", tabPrimary: 91, visualOrder: 113, title: "IT Security Management Plan & Review/Waiver", uid: "77", notes: "\u00b7 IT Security Plan submitted\n\u00b7 IT Security Management Plan submitted\n\u00b7 Evidence of review and approval by the Center Information Security Officer (CISO) for both Plans\n\u00b7 Contractor clause and applicable documents list waiver, IT Security Manager review, and copy of resulting modification (1804.470-4(b)) \n\u00b7 Plan waiver\n\u00b7 Plan updates submitted and evidence of review/concurrence" },
  { tab: "n/a", tabPrimary: null, visualOrder: 114, title: "Safety and Health Plan & Review", uid: "75", notes: "\u00b7 Safety and Health Plan submitted  \n\u00b7 Evidence of final review and concurrence by the subject matter expert (consultant) of plan submitted \n\u00b7 Plan updates submitted and evidence of review/concurrence" },
  { tab: "67 & 82", tabPrimary: 67, visualOrder: 115, title: "Small Business Subcontracting Plan & Reports/Waiver", uid: "76", notes: "\u00b7 Subcontracting Plan submitted \n\u00b7 Review of Subcontracting Plan \n\u00b7 Final approval of the plan and the final negotiated plan\n\u00b7 Evidence of final negotiated subcontracting plan submission to the SBA Procurement Center Rep \n\u00b7 Determination to Waive the Requirement for a Subcontracting Plan When No Subcontracting Possibilities Exist NASA HQ template\n\u00b7 Any notifications or communications with the Contractor related to the eSRS and the Contractor completing reports and/or meeting subcontracting goals" },
  { tab: "92", tabPrimary: 92, visualOrder: 116, title: "Total Compensation Plan (TCP)", uid: "123", notes: "\u00b7 Compensation Plan submitted\n\u00b7 Evidence of CO review of plan after award, at least every 3-years (1831.205-670(f)(g))" },
  { tab: "94 or n/a", tabPrimary: 94, visualOrder: 117, title: "Plans - Other (e.g., Phase-In Plan; Government Property Mgt Plan)", uid: "79", notes: "\u00b7 Plan(s) submitted  \n\u00b7 Evidence of final review and concurrence by the subject matter expert (consultant) of plan submitted \n\u00b7 Plan updates submitted and evidence of review/concurrence" },
  { tab: "51", tabPrimary: 51, visualOrder: 118, title: "Post-Award Overtime Premium Approval", uid: "120", notes: "\u00b7 Written request from the Contractor for overtime premiums\n\u00b7 CO approval/disapproval" },
  { tab: "79", tabPrimary: 79, visualOrder: 119, title: "Subcontract Consent", uid: "116", notes: "\u00b7 Contractor's subcontract consent request and supporting documentation\n\u00b7 Subcontract Consent Review NASA HQ template\n\u00b7 Documentation of considerations per FAR 44.202-2" },
  { tab: "18", tabPrimary: 18, visualOrder: 120, title: "Organizational Conflict of Interest (OCI)  Waiver/Decision", uid: "144", notes: "\u00b7 Documented OCI issues identified during award performance and resolution" },
  { tab: "n/a", tabPrimary: null, visualOrder: 121, title: "Authorization to use Govt supply sources", uid: "140", notes: "\u00b7 Authorization to Use Government Supply Sources NASA HQ template\n\u00b7 CO written finding supporting issuance of authorization" },
  { tab: "97", tabPrimary: 97, visualOrder: 122, title: "Government Property Request, Rentals & Transfers", uid: "128", notes: "\u00b7 Requests for additional property\n\u00b7 IPO coordination/review\n\u00b7 Transfer documentation" },
  { tab: "95", tabPrimary: 95, visualOrder: 123, title: "Foreign Travel Request/Approval/Debriefings", uid: "121", notes: "\u00b7 Foreign travel requests from contractor\n\u00b7 CO review of request\n\u00b7 Post-travel reports\n\u00b7 IT requests to CIO" },
  { tab: "80", tabPrimary: 80, visualOrder: 124, title: "NF 533 Reports and CO Analysis", uid: "117", notes: "\u00b7 All 533 reports, to include financial baseline plans\n\u00b7 NF 533 Monthly Analysis NASA HQ template or other evidence of 533 reviews\n\u00b7 When an overrun is indicated, copies of letters or documentation of telecoms or meetings discussing the overrun" },
  { tab: "80", tabPrimary: 80, visualOrder: 125, title: "Post-Award NF 533 Waiver Approval", uid: "118", notes: "\u00b7 NF 533Q Waiver" },
  { tab: "94", tabPrimary: 94, visualOrder: 126, title: "Earned Value Management (EVM) Documentation", uid: "124", notes: "\u00b7 EVMS ANSI/EIA-748 Standard Compliance Plan and associated review/approval\n\u00b7 All documentation related to Integrated Baseline Reviews\n\u00b7 Contractor request for EVMS changes and approval/disapproval\n\u00b7 Any applicable waivers\n\u00b7 Contractor request to implement over target vaseline or over target schedule and CO response\n\u00b7 Applicable corrective action plans" },
  { tab: "81", tabPrimary: 81, visualOrder: 127, title: "New Technology Report(s)", uid: "119", notes: "\u00b7 Copies of interim and final new technology or patent rights reports or notifications of delivery\n\u00b7 Contractor's request for limited rights or restricted computer software\n\u00b7 Invention rights documentation, if applicable\n\u00b7 Copy of License Agreement, if applicable\n\u00b7 Request for legal review, and disposition of comments" },
  { tab: "93", tabPrimary: 93, visualOrder: 128, title: "Construction Contract Project Labor Agreement Reporting", uid: "125", notes: "\u00b7 Construction contract project labor agreement reporting\n\u00b7 Communications related to labor standard reporting and requirements \n\u00b7 Semiannual enforcement report" },
  { tab: "83", tabPrimary: 83, visualOrder: 129, title: "Voucher/Invoice Backup Documents", uid: "133", notes: "The official contract invoice and supporting reviews/approvals are retained by NSSC Accounts Payable and are considered the official contract file. Invoices and review/approvals are not retained in NEAR. The NASA Voucher Review Checklist (cost type contract) NASA HQ template shall be filed with each voucher in the invoicing electronic system.\n\n\u00b7 Notice of assignment \n\u00b7 Documentation related to obtaining voucher/invoice clarification" },
  { tab: "n/a", tabPrimary: null, visualOrder: 130, title: "Deliverables - Other (monthly reports, final reports, etc.)", uid: "136", notes: "\u00b7 Deliverables that are not specifically addressed in another file element" },
  { tab: "85", tabPrimary: 85, visualOrder: 131, title: "Inspection/Acceptance Documents", uid: "131", notes: "\u00b7 DD Form 250, Material Inspection and Receiving Report\n\u00b7 Any other documentation submitted by the cognizant administrative office who may be authorized to accept material/services on behalf of the CO, e.g., major hardware procurements where they have an in-plant DCAS office\n\u00b7 Noncompliance reports for construction\n\u00b7 Utilities and construction permits\n\u00b7 Memos to the COR to determine if the Contractor has met the specific milestones or performance requirements" },
  { tab: "76", tabPrimary: 76, visualOrder: 132, title: "Award Fee/Award Term Plan/Performance Evaluation Board (PEB) Appointment", uid: "132", notes: "\u00b7 Award/incentive fee plan and any revisions\n\u00b7 Recommendations for award fee board membership\n\u00b7 Performance Evaluation Board (PEB) Appointment NASA HQ template\n\u00b7 Fee Determination Official (FDO) Appointment NASA HQ template" },
  { tab: "76 or 98", tabPrimary: 76, visualOrder: 133, title: "Award Fee (FDO)/Award Term Determination(s)", uid: "139", notes: "\u00b7 Award Term Determination NASA HQ template\n\u00b7 Award Fee Report\n\u00b7 Contractor Self-Evaluation\n\u00b7 Meeting minutes" },
  { tab: "84 or 86", tabPrimary: 84, visualOrder: 134, title: "Audit Reports/System Reviews", uid: "72", notes: "\u00b7 DCAA/DCMA Audit Reports\n\u00b7 Contractor Purchasing System Review (CPSR)\n\u00b7 Floorcheck audit and timekeeping systems review\n\u00b7 Insurance/pensions review\n\u00b7 Construction compliance check semi-annual review" },
  { tab: "98", tabPrimary: 98, visualOrder: 135, title: "Contractor Performance Evaluations (i.e., CPARS)", uid: "126", notes: "\u00b7 Contractor Performance Assessment Reports (CPAR) evaluation for each contract year. (CPARS is not the official repository.)\n\u00b7 CPARS Input NASA HQ template, if filled out by technical representative\n\u00b7 For SB set-asides, evidence that limitation on subcontracting is being monitored" },
  { tab: "99", tabPrimary: 99, visualOrder: 136, title: "Blanket Purchase Agreement (BPA) Annual Reviews", uid: "127", notes: "\u00b7 Blanket Purchase Agreement Annual Review NASA HQ template" },
  { tab: "n/a", tabPrimary: null, visualOrder: 137, title: "Duty Free Certificate", uid: "148", notes: "\u00b7 Duty Free Certificate NASA HQ template" },
  { tab: "n/a", tabPrimary: null, visualOrder: 138, title: "General Correspondence (Post-Award)", uid: "137", notes: "\u00b7 All general correspondence, documents, or requirements that are not specifically related to another post-awad file element" },
  { tab: "n/a", tabPrimary: null, visualOrder: 139, title: "Ratification", uid: "146", notes: "\u00b7 Ratification of Unauthorized Commitments NASA HQ template" },
  { tab: "n/a", tabPrimary: null, visualOrder: 140, title: "Termination", uid: "138", notes: "\u00b7 All correspondence, documents, or requirements related to the termination action\n\u00b7 Show Cause, Cure Notice\n\u00b7 Termination audits" },
  { tab: "100", tabPrimary: 100, visualOrder: 141, title: "Closeout Documentation", uid: "134", notes: "\u00b7 Checklist supporting documentation not readily available in existing FE (e.g., funds analysis)\n\u00b7 Documentation required by NFS Appendix B-105-1(c)" },
];

/** T-Minus template key to NEAR unique id. Only confirmed matches are listed. */
export const NEAR_TEMPLATE_UID: Record<string, string> = {
  "nf-1707": "1",
  "igce": "13",
  "sow": "4",
  "nf-1787": "7",
  "nf-1787a": "9",
  "market-research-memo": "9",
  "jofoc": "22",
  "fair-opportunity-brand-name": "24",
  "pnm": "82",
  "technical-evaluation-report": "74",
  "evaluation-of-quotations": "74",
  "cor-appointment": "114",
  "cpars-input": "126",
  "synopsis": "40",
  "blackout-notice": "59",
  "option-justification": "28",
};

const BY_UID = new Map(NEAR_ELEMENTS.map((e) => [e.uid, e]));

export function nearElementByUid(uid: string | null | undefined): NearElement | null {
  if (!uid) return null;
  return BY_UID.get(String(uid)) ?? null;
}

/** The checklist element for a T-Minus template key, when one is mapped. */
export function nearForTemplateKey(key: string | null | undefined): NearElement | null {
  if (!key) return null;
  const uid = NEAR_TEMPLATE_UID[key];
  return uid ? nearElementByUid(uid) : null;
}

/** Visual order on the NEAR file-element screen, by template key or unique id. */
export function nearVisualOrder(keyOrUid: string | null | undefined): number | null {
  const el = nearForTemplateKey(keyOrUid) ?? nearElementByUid(keyOrUid);
  return el ? el.visualOrder : null;
}

/** "Tab 13" as the checklist prints it, including labels like "Tab 2 or 36". */
export function nearTabLabel(tab: string | number | null | undefined): string {
  const text = String(tab ?? "").trim();
  return text === "" ? "Tab not recorded" : `Tab ${text}`;
}
