/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as CenterConfigRouteImport } from './routes/center-config'
import { Route as ChecksRouteImport } from './routes/checks'
import { Route as ClauseChangesRouteImport } from './routes/clause-changes'
import { Route as DeviationsRouteImport } from './routes/deviations'
import { Route as DigestRouteImport } from './routes/digest'
import { Route as DirectivesRouteImport } from './routes/directives'
import { Route as EscalationsRouteImport } from './routes/escalations'
import { Route as EstimateRouteImport } from './routes/estimate'
import { Route as FilesRouteImport } from './routes/files'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as PgpdQueueRouteImport } from './routes/pgpd-queue'
import { Route as RegIntakeRouteImport } from './routes/reg-intake'
import { Route as ReportingRouteImport } from './routes/reporting'
import { Route as ScorecardRouteImport } from './routes/scorecard'
import { Route as SeedStatusRouteImport } from './routes/seed-status'
import { Route as SimulateRouteImport } from './routes/simulate'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as WorkQueueRouteImport } from './routes/work-queue'
import { Route as DeviationsDeviationIdRouteImport } from './routes/deviations_.$deviationId'
import { Route as FilesAcquisitionIdRouteImport } from './routes/files_.$acquisitionId'
import { Route as IntakeAcquisitionIdRouteImport } from './routes/intake_.$acquisitionId'
import { Route as SharedTokenRouteImport } from './routes/shared.$token'
import { Route as DocumentsTemplateKeyIndexRouteImport } from './routes/documents.$templateKey.index'
import { Route as DocumentsTemplateKeyAcquisitionIdRouteImport } from './routes/documents.$templateKey.$acquisitionId'
import { Route as ApiPublicHooksExclusionsSweepRouteImport } from './routes/api/public/hooks/exclusions-sweep'
import { Route as ApiPublicHooksReportingExtractRouteImport } from './routes/api/public/hooks/reporting-extract'
import { Route as ApiPublicHooksWatchRefreshRouteImport } from './routes/api/public/hooks/watch-refresh'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const CenterConfigRoute = CenterConfigRouteImport.update({
  id: '/center-config',
  path: '/center-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecksRoute = ChecksRouteImport.update({
  id: '/checks',
  path: '/checks',
  getParentRoute: () => rootRouteImport,
} as any)
const ClauseChangesRoute = ClauseChangesRouteImport.update({
  id: '/clause-changes',
  path: '/clause-changes',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviationsRoute = DeviationsRouteImport.update({
  id: '/deviations',
  path: '/deviations',
  getParentRoute: () => rootRouteImport,
} as any)
const DigestRoute = DigestRouteImport.update({
  id: '/digest',
  path: '/digest',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectivesRoute = DirectivesRouteImport.update({
  id: '/directives',
  path: '/directives',
  getParentRoute: () => rootRouteImport,
} as any)
const EscalationsRoute = EscalationsRouteImport.update({
  id: '/escalations',
  path: '/escalations',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateRoute = EstimateRouteImport.update({
  id: '/estimate',
  path: '/estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const PgpdQueueRoute = PgpdQueueRouteImport.update({
  id: '/pgpd-queue',
  path: '/pgpd-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const RegIntakeRoute = RegIntakeRouteImport.update({
  id: '/reg-intake',
  path: '/reg-intake',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingRoute = ReportingRouteImport.update({
  id: '/reporting',
  path: '/reporting',
  getParentRoute: () => rootRouteImport,
} as any)
const ScorecardRoute = ScorecardRouteImport.update({
  id: '/scorecard',
  path: '/scorecard',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedStatusRoute = SeedStatusRouteImport.update({
  id: '/seed-status',
  path: '/seed-status',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulateRoute = SimulateRouteImport.update({
  id: '/simulate',
  path: '/simulate',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkQueueRoute = WorkQueueRouteImport.update({
  id: '/work-queue',
  path: '/work-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviationsDeviationIdRoute = DeviationsDeviationIdRouteImport.update({
  id: '/deviations_/$deviationId',
  path: '/deviations/$deviationId',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesAcquisitionIdRoute = FilesAcquisitionIdRouteImport.update({
  id: '/files_/$acquisitionId',
  path: '/files/$acquisitionId',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeAcquisitionIdRoute = IntakeAcquisitionIdRouteImport.update({
  id: '/intake_/$acquisitionId',
  path: '/intake/$acquisitionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedTokenRoute = SharedTokenRouteImport.update({
  id: '/shared/$token',
  path: '/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsTemplateKeyIndexRoute =
  DocumentsTemplateKeyIndexRouteImport.update({
    id: '/documents/$templateKey/',
    path: '/documents/$templateKey/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocumentsTemplateKeyAcquisitionIdRoute =
  DocumentsTemplateKeyAcquisitionIdRouteImport.update({
    id: '/documents/$templateKey/$acquisitionId',
    path: '/documents/$templateKey/$acquisitionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksExclusionsSweepRoute =
  ApiPublicHooksExclusionsSweepRouteImport.update({
    id: '/api/public/hooks/exclusions-sweep',
    path: '/api/public/hooks/exclusions-sweep',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksReportingExtractRoute =
  ApiPublicHooksReportingExtractRouteImport.update({
    id: '/api/public/hooks/reporting-extract',
    path: '/api/public/hooks/reporting-extract',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWatchRefreshRoute =
  ApiPublicHooksWatchRefreshRouteImport.update({
    id: '/api/public/hooks/watch-refresh',
    path: '/api/public/hooks/watch-refresh',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/audit-log': typeof AuditLogRoute
  '/center-config': typeof CenterConfigRoute
  '/checks': typeof ChecksRoute
  '/clause-changes': typeof ClauseChangesRoute
  '/deviations': typeof DeviationsRoute
  '/digest': typeof DigestRoute
  '/directives': typeof DirectivesRoute
  '/escalations': typeof EscalationsRoute
  '/estimate': typeof EstimateRoute
  '/files': typeof FilesRoute
  '/intake': typeof IntakeRoute
  '/pgpd-queue': typeof PgpdQueueRoute
  '/reg-intake': typeof RegIntakeRoute
  '/reporting': typeof ReportingRoute
  '/scorecard': typeof ScorecardRoute
  '/seed-status': typeof SeedStatusRoute
  '/simulate': typeof SimulateRoute
  '/templates': typeof TemplatesRoute
  '/watch': typeof WatchRoute
  '/work-queue': typeof WorkQueueRoute
  '/deviations/$deviationId': typeof DeviationsDeviationIdRoute
  '/files/$acquisitionId': typeof FilesAcquisitionIdRoute
  '/intake/$acquisitionId': typeof IntakeAcquisitionIdRoute
  '/shared/$token': typeof SharedTokenRoute
  '/documents/$templateKey/$acquisitionId': typeof DocumentsTemplateKeyAcquisitionIdRoute
  '/documents/$templateKey/': typeof DocumentsTemplateKeyIndexRoute
  '/api/public/hooks/exclusions-sweep': typeof ApiPublicHooksExclusionsSweepRoute
  '/api/public/hooks/reporting-extract': typeof ApiPublicHooksReportingExtractRoute
  '/api/public/hooks/watch-refresh': typeof ApiPublicHooksWatchRefreshRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/audit-log': typeof AuditLogRoute
  '/center-config': typeof CenterConfigRoute
  '/checks': typeof ChecksRoute
  '/clause-changes': typeof ClauseChangesRoute
  '/deviations': typeof DeviationsRoute
  '/digest': typeof DigestRoute
  '/directives': typeof DirectivesRoute
  '/escalations': typeof EscalationsRoute
  '/estimate': typeof EstimateRoute
  '/files': typeof FilesRoute
  '/intake': typeof IntakeRoute
  '/pgpd-queue': typeof PgpdQueueRoute
  '/reg-intake': typeof RegIntakeRoute
  '/reporting': typeof ReportingRoute
  '/scorecard': typeof ScorecardRoute
  '/seed-status': typeof SeedStatusRoute
  '/simulate': typeof SimulateRoute
  '/templates': typeof TemplatesRoute
  '/watch': typeof WatchRoute
  '/work-queue': typeof WorkQueueRoute
  '/deviations/$deviationId': typeof DeviationsDeviationIdRoute
  '/files/$acquisitionId': typeof FilesAcquisitionIdRoute
  '/intake/$acquisitionId': typeof IntakeAcquisitionIdRoute
  '/shared/$token': typeof SharedTokenRoute
  '/documents/$templateKey/$acquisitionId': typeof DocumentsTemplateKeyAcquisitionIdRoute
  '/documents/$templateKey': typeof DocumentsTemplateKeyIndexRoute
  '/api/public/hooks/exclusions-sweep': typeof ApiPublicHooksExclusionsSweepRoute
  '/api/public/hooks/reporting-extract': typeof ApiPublicHooksReportingExtractRoute
  '/api/public/hooks/watch-refresh': typeof ApiPublicHooksWatchRefreshRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/audit-log': typeof AuditLogRoute
  '/center-config': typeof CenterConfigRoute
  '/checks': typeof ChecksRoute
  '/clause-changes': typeof ClauseChangesRoute
  '/deviations': typeof DeviationsRoute
  '/digest': typeof DigestRoute
  '/directives': typeof DirectivesRoute
  '/escalations': typeof EscalationsRoute
  '/estimate': typeof EstimateRoute
  '/files': typeof FilesRoute
  '/intake': typeof IntakeRoute
  '/pgpd-queue': typeof PgpdQueueRoute
  '/reg-intake': typeof RegIntakeRoute
  '/reporting': typeof ReportingRoute
  '/scorecard': typeof ScorecardRoute
  '/seed-status': typeof SeedStatusRoute
  '/simulate': typeof SimulateRoute
  '/templates': typeof TemplatesRoute
  '/watch': typeof WatchRoute
  '/work-queue': typeof WorkQueueRoute
  '/deviations_/$deviationId': typeof DeviationsDeviationIdRoute
  '/files_/$acquisitionId': typeof FilesAcquisitionIdRoute
  '/intake_/$acquisitionId': typeof IntakeAcquisitionIdRoute
  '/shared/$token': typeof SharedTokenRoute
  '/documents/$templateKey/$acquisitionId': typeof DocumentsTemplateKeyAcquisitionIdRoute
  '/documents/$templateKey/': typeof DocumentsTemplateKeyIndexRoute
  '/api/public/hooks/exclusions-sweep': typeof ApiPublicHooksExclusionsSweepRoute
  '/api/public/hooks/reporting-extract': typeof ApiPublicHooksReportingExtractRoute
  '/api/public/hooks/watch-refresh': typeof ApiPublicHooksWatchRefreshRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcements'
    | '/audit-log'
    | '/center-config'
    | '/checks'
    | '/clause-changes'
    | '/deviations'
    | '/digest'
    | '/directives'
    | '/escalations'
    | '/estimate'
    | '/files'
    | '/intake'
    | '/pgpd-queue'
    | '/reg-intake'
    | '/reporting'
    | '/scorecard'
    | '/seed-status'
    | '/simulate'
    | '/templates'
    | '/watch'
    | '/work-queue'
    | '/deviations/$deviationId'
    | '/files/$acquisitionId'
    | '/intake/$acquisitionId'
    | '/shared/$token'
    | '/documents/$templateKey/$acquisitionId'
    | '/documents/$templateKey/'
    | '/api/public/hooks/exclusions-sweep'
    | '/api/public/hooks/reporting-extract'
    | '/api/public/hooks/watch-refresh'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/audit-log'
    | '/center-config'
    | '/checks'
    | '/clause-changes'
    | '/deviations'
    | '/digest'
    | '/directives'
    | '/escalations'
    | '/estimate'
    | '/files'
    | '/intake'
    | '/pgpd-queue'
    | '/reg-intake'
    | '/reporting'
    | '/scorecard'
    | '/seed-status'
    | '/simulate'
    | '/templates'
    | '/watch'
    | '/work-queue'
    | '/deviations/$deviationId'
    | '/files/$acquisitionId'
    | '/intake/$acquisitionId'
    | '/shared/$token'
    | '/documents/$templateKey/$acquisitionId'
    | '/documents/$templateKey'
    | '/api/public/hooks/exclusions-sweep'
    | '/api/public/hooks/reporting-extract'
    | '/api/public/hooks/watch-refresh'
  id:
    | '__root__'
    | '/'
    | '/announcements'
    | '/audit-log'
    | '/center-config'
    | '/checks'
    | '/clause-changes'
    | '/deviations'
    | '/digest'
    | '/directives'
    | '/escalations'
    | '/estimate'
    | '/files'
    | '/intake'
    | '/pgpd-queue'
    | '/reg-intake'
    | '/reporting'
    | '/scorecard'
    | '/seed-status'
    | '/simulate'
    | '/templates'
    | '/watch'
    | '/work-queue'
    | '/deviations_/$deviationId'
    | '/files_/$acquisitionId'
    | '/intake_/$acquisitionId'
    | '/shared/$token'
    | '/documents/$templateKey/$acquisitionId'
    | '/documents/$templateKey/'
    | '/api/public/hooks/exclusions-sweep'
    | '/api/public/hooks/reporting-extract'
    | '/api/public/hooks/watch-refresh'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  AuditLogRoute: typeof AuditLogRoute
  CenterConfigRoute: typeof CenterConfigRoute
  ChecksRoute: typeof ChecksRoute
  ClauseChangesRoute: typeof ClauseChangesRoute
  DeviationsRoute: typeof DeviationsRoute
  DigestRoute: typeof DigestRoute
  DirectivesRoute: typeof DirectivesRoute
  EscalationsRoute: typeof EscalationsRoute
  EstimateRoute: typeof EstimateRoute
  FilesRoute: typeof FilesRoute
  IntakeRoute: typeof IntakeRoute
  PgpdQueueRoute: typeof PgpdQueueRoute
  RegIntakeRoute: typeof RegIntakeRoute
  ReportingRoute: typeof ReportingRoute
  ScorecardRoute: typeof ScorecardRoute
  SeedStatusRoute: typeof SeedStatusRoute
  SimulateRoute: typeof SimulateRoute
  TemplatesRoute: typeof TemplatesRoute
  WatchRoute: typeof WatchRoute
  WorkQueueRoute: typeof WorkQueueRoute
  DeviationsDeviationIdRoute: typeof DeviationsDeviationIdRoute
  FilesAcquisitionIdRoute: typeof FilesAcquisitionIdRoute
  IntakeAcquisitionIdRoute: typeof IntakeAcquisitionIdRoute
  SharedTokenRoute: typeof SharedTokenRoute
  DocumentsTemplateKeyAcquisitionIdRoute: typeof DocumentsTemplateKeyAcquisitionIdRoute
  DocumentsTemplateKeyIndexRoute: typeof DocumentsTemplateKeyIndexRoute
  ApiPublicHooksExclusionsSweepRoute: typeof ApiPublicHooksExclusionsSweepRoute
  ApiPublicHooksReportingExtractRoute: typeof ApiPublicHooksReportingExtractRoute
  ApiPublicHooksWatchRefreshRoute: typeof ApiPublicHooksWatchRefreshRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/center-config': {
      id: '/center-config'
      path: '/center-config'
      fullPath: '/center-config'
      preLoaderRoute: typeof CenterConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checks': {
      id: '/checks'
      path: '/checks'
      fullPath: '/checks'
      preLoaderRoute: typeof ChecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clause-changes': {
      id: '/clause-changes'
      path: '/clause-changes'
      fullPath: '/clause-changes'
      preLoaderRoute: typeof ClauseChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deviations': {
      id: '/deviations'
      path: '/deviations'
      fullPath: '/deviations'
      preLoaderRoute: typeof DeviationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digest': {
      id: '/digest'
      path: '/digest'
      fullPath: '/digest'
      preLoaderRoute: typeof DigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directives': {
      id: '/directives'
      path: '/directives'
      fullPath: '/directives'
      preLoaderRoute: typeof DirectivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escalations': {
      id: '/escalations'
      path: '/escalations'
      fullPath: '/escalations'
      preLoaderRoute: typeof EscalationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimate': {
      id: '/estimate'
      path: '/estimate'
      fullPath: '/estimate'
      preLoaderRoute: typeof EstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pgpd-queue': {
      id: '/pgpd-queue'
      path: '/pgpd-queue'
      fullPath: '/pgpd-queue'
      preLoaderRoute: typeof PgpdQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reg-intake': {
      id: '/reg-intake'
      path: '/reg-intake'
      fullPath: '/reg-intake'
      preLoaderRoute: typeof RegIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting': {
      id: '/reporting'
      path: '/reporting'
      fullPath: '/reporting'
      preLoaderRoute: typeof ReportingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scorecard': {
      id: '/scorecard'
      path: '/scorecard'
      fullPath: '/scorecard'
      preLoaderRoute: typeof ScorecardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seed-status': {
      id: '/seed-status'
      path: '/seed-status'
      fullPath: '/seed-status'
      preLoaderRoute: typeof SeedStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulate': {
      id: '/simulate'
      path: '/simulate'
      fullPath: '/simulate'
      preLoaderRoute: typeof SimulateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-queue': {
      id: '/work-queue'
      path: '/work-queue'
      fullPath: '/work-queue'
      preLoaderRoute: typeof WorkQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deviations_/$deviationId': {
      id: '/deviations_/$deviationId'
      path: '/deviations/$deviationId'
      fullPath: '/deviations/$deviationId'
      preLoaderRoute: typeof DeviationsDeviationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files_/$acquisitionId': {
      id: '/files_/$acquisitionId'
      path: '/files/$acquisitionId'
      fullPath: '/files/$acquisitionId'
      preLoaderRoute: typeof FilesAcquisitionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake_/$acquisitionId': {
      id: '/intake_/$acquisitionId'
      path: '/intake/$acquisitionId'
      fullPath: '/intake/$acquisitionId'
      preLoaderRoute: typeof IntakeAcquisitionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$token': {
      id: '/shared/$token'
      path: '/shared/$token'
      fullPath: '/shared/$token'
      preLoaderRoute: typeof SharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$templateKey/': {
      id: '/documents/$templateKey/'
      path: '/documents/$templateKey'
      fullPath: '/documents/$templateKey/'
      preLoaderRoute: typeof DocumentsTemplateKeyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$templateKey/$acquisitionId': {
      id: '/documents/$templateKey/$acquisitionId'
      path: '/documents/$templateKey/$acquisitionId'
      fullPath: '/documents/$templateKey/$acquisitionId'
      preLoaderRoute: typeof DocumentsTemplateKeyAcquisitionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/exclusions-sweep': {
      id: '/api/public/hooks/exclusions-sweep'
      path: '/api/public/hooks/exclusions-sweep'
      fullPath: '/api/public/hooks/exclusions-sweep'
      preLoaderRoute: typeof ApiPublicHooksExclusionsSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/reporting-extract': {
      id: '/api/public/hooks/reporting-extract'
      path: '/api/public/hooks/reporting-extract'
      fullPath: '/api/public/hooks/reporting-extract'
      preLoaderRoute: typeof ApiPublicHooksReportingExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/watch-refresh': {
      id: '/api/public/hooks/watch-refresh'
      path: '/api/public/hooks/watch-refresh'
      fullPath: '/api/public/hooks/watch-refresh'
      preLoaderRoute: typeof ApiPublicHooksWatchRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  AuditLogRoute: AuditLogRoute,
  CenterConfigRoute: CenterConfigRoute,
  ChecksRoute: ChecksRoute,
  ClauseChangesRoute: ClauseChangesRoute,
  DeviationsRoute: DeviationsRoute,
  DigestRoute: DigestRoute,
  DirectivesRoute: DirectivesRoute,
  EscalationsRoute: EscalationsRoute,
  EstimateRoute: EstimateRoute,
  FilesRoute: FilesRoute,
  IntakeRoute: IntakeRoute,
  PgpdQueueRoute: PgpdQueueRoute,
  RegIntakeRoute: RegIntakeRoute,
  ReportingRoute: ReportingRoute,
  ScorecardRoute: ScorecardRoute,
  SeedStatusRoute: SeedStatusRoute,
  SimulateRoute: SimulateRoute,
  TemplatesRoute: TemplatesRoute,
  WatchRoute: WatchRoute,
  WorkQueueRoute: WorkQueueRoute,
  DeviationsDeviationIdRoute: DeviationsDeviationIdRoute,
  FilesAcquisitionIdRoute: FilesAcquisitionIdRoute,
  IntakeAcquisitionIdRoute: IntakeAcquisitionIdRoute,
  SharedTokenRoute: SharedTokenRoute,
  DocumentsTemplateKeyAcquisitionIdRoute:
    DocumentsTemplateKeyAcquisitionIdRoute,
  DocumentsTemplateKeyIndexRoute: DocumentsTemplateKeyIndexRoute,
  ApiPublicHooksExclusionsSweepRoute: ApiPublicHooksExclusionsSweepRoute,
  ApiPublicHooksReportingExtractRoute: ApiPublicHooksReportingExtractRoute,
  ApiPublicHooksWatchRefreshRoute: ApiPublicHooksWatchRefreshRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
